name: Deploy to AWS Lambda

on:
  push:
    branches: [ "dev" ]
env: 
    AWS_REGION: "us-west-2"
    audience: "sts.amazonaws.com"

permissions:
  id-token: write   # This is required for OIDC authentication
  contents: read    # This is required to checkout the repository

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        audience: ${{ env.audience }}
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }} // TODO add this as a secret to the repo
        aws-region: ${{ env.AWS_REGION }}
        # The role-to-assume should be the ARN of the IAM role you created for GitHub Actions OIDC

    - name: Deploy Lambda Function
      uses: aws-actions/aws-lambda-deploy@v1.1.0
      with:
        function-name: my-function-name
        code-artifacts-dir: my-code-artifacts-dir
        handler: index.handler
        runtime: nodejs22.x
        # Add any additional inputs this action supports